apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Walterspieler-II
  annotations:
    github.com/project-slug: walterspieler/Walterspieler-II
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://www.walterspieler.com/
  links:
    - url: https://www.walterspieler.com
      title: Portfolio Walterspieler
      icon: ColorLens
      type: protfolio
spec:
  type: other
  lifecycle: unknown
  owner: walterspieler
